### ISSUE TITLE
Update the installation via CocoaPods

### ISSUE THREAD

**Issue by frameorigin** [tesseract-one/JsonRPC.swift#5]
At the moment, the installation instructions via CocoaPods are as follows:
`pod 'JsonRPC.swift', '~> 0.1.0'`

However, the current version can only be installed if you use the following command"
`pod 'JsonRPC.swift', :git => 'https://github.com/tesseract-one/JsonRPC.swift', :branch => 'main'`

**Comment by ypopovych** [comment]
we didn't release a new version yet. It will be released as 0.2.0
