### ISSUE TITLE
"Key not found" even though keys & json look fine 

### ISSUE THREAD

**Issue by Bochelly** [tesseract-one/JsonRPC.swift#6]
Thanks for this awesome package! I keep getting this error while my mapping looks fine. Any idea of what I could do wrong? Many thanks

**Logs (json reponse & error)**
Json reponse:
<img width="845" alt="image" src="https://github.com/tesseract-one/JsonRPC.swift/assets/55988496/743dbb13-9fa1-4cf0-af4b-906f50da8ccc">
Error:
<img width="836" alt="image" src="https://github.com/tesseract-one/JsonRPC.swift/assets/55988496/2c1bcf30-1794-42aa-97fe-3ebe28e1a806">

**Code (call & mapping)**
Call:
<img width="961" alt="image" src="https://github.com/tesseract-one/JsonRPC.swift/assets/55988496/8529cc15-c406-4b4f-a684-a02e95b864b1">
Mapping:
<img width="565" alt="image" src="https://github.com/tesseract-one/JsonRPC.swift/assets/55988496/65dae6fe-b1e2-4201-944c-94a8d680ff6e">

**Comment by ypopovych** [comment]
You don't have to parse the entire response. Only "result" property. Remove top-level struct with "id" and "jsonrpc" fields.

**Comment by Bochelly** [comment]
That worked, many thanks 🙏
I thought the method should be used like `JSONDecoder().decode`
